WoM/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('recipes.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('comments/', include('django_comments_xtd.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path, include

from . import views

app_name = 'recipes'
urlpatterns = [
    path('', views.home, name='home'),
    # path('login', views.login, name = 'login'),
    # path('loggedIn', views.loggedIn, name = 'loggedIn'),
    path('profile/<int:pk>', views.profile, name = 'profile'),
    path('profile/<int:pk>/edit/', views.ProfileUpdateView.as_view(), name = "editprofile"),
    #path('profile/<int:pk>/update/', views.updateProfile, name = "updateProfile"),
    path('recipes/form/', views.get_recipe, name = 'recipeform'),
    path('recipes/list/', views.RecipeListView.as_view(), name = 'recipelist'),
    path('recipes/<int:pk>/', views.RecipeView.as_view(), name = 'recipe'),
    path('recipes/fork/<int:pk>/', views.fork_recipe, name = "forkrecipe"),
    path('<int:recipe_id>/<int:user_id>', views.favorite, name = "favorite"),
    # for account authentication
    path('accounts/', include('allauth.urls')),
    # for comments
    path('recipes/<int:pk>/comments/', include('django_comments_xtd.urls')),
]

recipes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class Recipe(models.Model):
    recipe_title = models.CharField(max_length=100)
    recipe_ingredients = models.CharField(max_length=5000, help_text='Separate ingredients with a semicolon, please.')
    recipe_instructions = models.CharField(max_length=5000, null=True, help_text='Separate instructions with a semicolon, please.')
    pub_date = models.DateTimeField(auto_now_add=True)
    parent = models.ForeignKey(
        'self',
        on_delete=models.PROTECT,
        blank=True,
        null=True,
    )
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    img = models.ImageField(upload_to='recipe_images/', blank=True, null=True)
    favorite = models.ManyToManyField(
        User, 
        related_name='favorites',
    )

    def get_absolute_url(self):
        return reverse('recipes:recipe', kwargs={"pk": self.pk})
    

    def __str__(self):
        return self.recipe_title

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # implement this when we have an image database
    # avatar = models.ImageField(default = 'default.jpg', upload_to = 'profile_images')
    gender = models.CharField(max_length=15, null=True, blank=True)
    birthday = models.DateField(null=True, blank=True)
    bio = models.TextField()
    
    # implement this when our recipe database is updated
    # saved_recipes =
    # created_recipes =

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username

recipes/forms.py
from django import forms
from recipes.models import Recipe

class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['recipe_title', 'recipe_ingredients', 'recipe_instructions', 'img']

recipes/views.py
from django.shortcuts import get_object_or_404, render
from django.views import generic
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.models import User
from django.db.models import Count

from .forms import RecipeForm
from .models import Recipe, Profile

def home(request):
    # recipe_list = Recipe.objects.exclude(img__exact='')[:3]
    topfavs = Recipe.objects.annotate(num_favs=Count('favorite')).order_by('-num_favs').exclude(img__exact='')[:3]
    # topfavs[0].num_favs
    return render(request, 'recipes/home.html', {'recipe_list': topfavs})

def profile(request, pk): 
    user = get_object_or_404(User, pk = pk)
    try: 
        profile = user.profile
    except (Profile.DoesNotExist):
        profile = Profile()
        profile.user = user
        profile.save()
        return HttpResponseRedirect(reverse('recipes:editprofile', args=(profile.id,)))
    favorites = user.favorites.all()
    authored = user.recipe_set.all()
    return render(request, 'recipes/profile.html', {'profile': profile, 'favorites': favorites, 'authored': authored})

@method_decorator(login_required, name='dispatch')
class ProfileUpdateView(generic.UpdateView):
    model = Profile
    fields = ['gender', 'birthday', 'bio']
    template_name = 'recipes/editprofile.html'
    def get_success_url(self):
        return reverse('recipes:profile', kwargs={'pk': self.object.user.id})

# Handles recipe submission. By default it takes you to the form to submit a recipe. 
# When you submit a recipe, it can handle the data and redirect to the new recipe page
def get_recipe(request):
    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES)
        if form.is_valid():
            recipe = form.save(commit=False)
            recipe.author = request.user
            recipe.save()
            return HttpResponseRedirect(reverse('recipes:recipe', args=(recipe.id,)))
    else:
        form = RecipeForm()

    return render(request, 'recipes/recipeform.html', {'form': form})

def fork_recipe(request, pk):
    parent = get_object_or_404(Recipe, pk=pk)
    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES)
        if form.is_valid():
            recipe = form.save(commit=False)
            recipe.parent = parent
            recipe.author = request.user
            recipe.save()
            if (recipe.img == None):
                recipe.img = parent.img
                recipe.save(update_fields=['img'])
            return HttpResponseRedirect(reverse('recipes:recipe', args=(recipe.id,)))
    else:
        form = RecipeForm(
            {'recipe_title': parent.recipe_title, 
            'recipe_ingredients': parent.recipe_ingredients, 
            'recipe_instructions': parent.recipe_instructions, },
            initial={'img': parent.img}
        )
    return render(request, 'recipes/recipeform.html', {'form': form, 'recipe': parent})

# Brings you to the list of recipes, ordered by date submitted
class RecipeListView(generic.ListView):
    model = Recipe
    template_name = 'recipes/recipelist.html'
    context_object_name = 'recipes_list'

    def get_queryset(self):
        return Recipe.objects.order_by('pub_date').annotate(num_favs=Count('favorite'))

class RecipeView(generic.DetailView):
    model = Recipe
    template_name = 'recipes/recipe.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_set'] = self.get_object().favorite.all()
        return context

def favorite(request, recipe_id, user_id):
    recipe = Recipe.objects.get(pk = recipe_id)
    user = User.objects.get(pk = user_id)
    if request.method == 'POST':
        next = request.POST.get('next', '/')
        try:
            user.favorites.get(pk = recipe_id)
        except (Recipe.DoesNotExist):
            user.favorites.add(recipe)
        else:
            user.favorites.remove(recipe)
    return HttpResponseRedirect(next)

recipes/templates/recipes/base.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    {% load custom_tags %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=2.0, minimum-scale=1.0">
    <meta name="authors" content="">
    <meta name="description" content="{% block description %}{% endblock %}" />
    <title>{% block title %}{% endblock %}</title>

    <!--    Generic Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">


    <!--    Custom Bootstrap Theme-->
    <link rel="stylesheet" href="{% static 'bootstrap.css' %}">

    <!-- CSS Stylesheet -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

    <!--    Favicon-->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon-16x16.png' %}">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"
          integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog=="
          crossorigin="anonymous"/>


</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'recipes:home' %}">Word of Mouth</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'recipes:home' %}">Home</a>
                </li>
<!--                <li class="nav-item">-->
<!--                    <a class="nav-link" href="#">Link</a>-->
<!--                </li>-->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Recipes
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'recipes:recipeform' %}">Add a Recipe</a></li>
                        <li><a class="dropdown-item" href="{% url 'recipes:recipelist' %}">See the List of Recipes</a></li>
<!--                        <li><hr class="dropdown-divider"></li>-->
                    </ul>
                </li>
            </ul>

<!--            LOGIN SECTION OF NAVBAR-->

            {% load socialaccount %}
            {% if user.is_authenticated %}
                <ul class="navbar-nav nav nav-item navbar-right">
                    <li class="vertical-center nav-link active"><a href = "{% url 'recipes:profile' user.id %}">{{user.username}}</a></li>
                    <li><a class="nav-link" href="/accounts/logout/"><button type="button" class="btn btn-primary">Log Out</button></a></li>
                </ul>
            {% else %}
                <ul class="navbar-nav nav nav-item navbar-right">
                    <li class="vertical-center nav-link active">You are not logged in</li>
                    <li><a class="nav-link" href="{% provider_login_url 'google' %}?next={{request.path}}"><button type="button" class="btn btn-primary">Login With Google</button></a></li>
                </ul>
            {% endif %}
<!--            END LOGIN SECTION OF NAVBAR-->

        </div>
    </div>
</nav>

{% block content %}
{% endblock %}

<!--Scripts necessary to make navbar work-->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

</body>
</html>

recipes/templates/recipes/editedrecipe.html
<h1>{{ editedrecipe.recipe_title }}</h1>
<p>
    {{ editedrecipe.recipe_instructions}}
</p>

recipes/templates/recipes/editedrecipelist.html
{% if editedrecipes_list %}
<ul class="list-group">
    {% for recipe in recipes_list %}
    <li class="list-group-item"><a href="{% url 'recipes:editedrecipe' editedrecipe.id %}">{{ editedrecipe.recipe_title }}</a></li>
    {% endfor %}
</ul>

{% else %}
<p>Waiting for recipes.</p>
{% endif %}

recipes/templates/recipes/editprofile.html
{% extends "recipes/base.html" %}

{% load static %}
{% load custom_tags %}

{% block description %}Profile Page{% endblock %}
{% block title %}Profile Page{% endblock %}

{% block content %}

<div class="container main bg-light">
    <div class="row banner">

        <h1>Edit Profile</h1>

    </div>
    <div class="row">
        {% if user.name == profile.user.name %}
        <form method="post">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Update">
        </form>
        {% else %}
        <p> This is not your profile to edit. <a href = "{% url 'recipes:profile' user.id %}"> Return to this profile </a></p>
        {% endif %}
    </div>
</div>

{% endblock %}

recipes/templates/recipes/home.html
{% extends "recipes/base.html" %}

{% load static %}
{% load custom_tags %}

{% block description %}Welcome page{% endblock %}
{% block title %}Welcome to Word of Mouth{% endblock %}

{% block content %}
<div class="container-fluid frontpage-head">
    <div class="row frontpage-row">

        <div class="col-md-8">
            <h1>Word of Mouth</h1>
            <h4>Where you can get the latest bites.</h4>
            <br><br><br>
            <h4>Check out recipes others have posted, or log in to post some of your own!</h4>
            <h4>Have fun <em>forking</em> them and putting your own fresh spin on them, too!</h4>
            <br>
            <a class="nav-link" href="{% url 'recipes:recipelist' %}"><button type="button" class="btn btn-primary">See the List of Recipes</button></a>

        </div>
        <div class="col-md-4">
            <img class="title-image" src="{% static 'fork.png' %}" alt="A fork with spaghetti on it">
        </div>

    </div>

</div>


<div class="container top-recipes">
    <h2>Top Recipes</h2>
    <div class="row top-recipes-cards">

        {% for item in recipe_list %}
        <div class="col-md-4">
            <div class="card">
                <a href="{% url 'recipes:recipe' item.pk %}">
                    <img src="{% static ''%}{{ item.img }}" class="card-img-top" alt="...">
                </a>
                <div class="card-body">
                    <h5 class="card-title">{{ item.recipe_title }}</h5>
                    <p class="card-text">
                        <a href="{% url 'recipes:recipe' item.pk %}">Get this recipe!</a>
                        <p>Favorited {{ item.num_favs }} time{{ item.num_favs | pluralize:",s" }}</p>
                    </p>
                </div>
            </div>
        </div>

        {% endfor %}
    </div>
</div>

{% endblock %}

recipes/templates/recipes/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% load socialaccount %}
    {% if user.is_authenticated %}
      <p>Welcome, {{ user.username }}!</p>
        <!--This line below needs to be able to grab its own pk somehow. 
        Temp will just be 1 but we need a manner to get login user's pk-->
        <a href="{% url 'recipes:profile' 1%}">View Profile</a>
    <a href=""></a>
    {% else %}
        <h2>Welcome to Word of Mouth! Please login to continue.</h2>
        <a href="{% provider_login_url 'google' %}">Login With Google</a>
    {% endif %}
</body>
</html>

recipes/templates/recipes/profile.html
{% extends "recipes/base.html" %}

{% load static %}
{% load custom_tags %}

{% block description %}Profile Page{% endblock %}
{% block title %}Profile Page{% endblock %}

{% block content %}

<div class="container main bg-light">
    <div class="row banner">
        <h1>This is the profile page for {{profile.user.username}}</h1>
    </div>

    <div class="row my-3 p-3">
        <p> Gender: {{profile.gender}}</p>
        <p> Birthday: {{profile.birthday}} </p>
        <p> Bio: {{profile.bio}}</p>
        <p> Created: {{profile.created_at}}</p>
        <p> Last edited: {{profile.updated_at}} </p>
        <h3>Authored Recipes:</h3> 
        <ul>
            {% if authored %}
            {% for item in authored %}
            <div class="col-md-4">
                <div class="card">
                    <a href="{% url 'recipes:recipe' item.pk %}">
                        {% if item.img %}
                        <img src="{% static ''%}{{ item.img }}" class="card-img-top" alt="...">
                        {% endif %}
                    </a>
                    <div class="card-body">
                        <h5 class="card-title">{{ item.recipe_title }}</h5>
                        <p class="card-text">
                            <a href="{% url 'recipes:recipe' item.pk %}">View this Recipe</a>
                            <form action="{% url 'recipes:favorite' item.id user.id %}" method='POST'>
                                {% csrf_token %}
                                <input type="hidden" name="next" value="{{ request.path }}">
                                {% if item in favorites %}
                                <input type="submit" value="Remove Favorite">
                                {% else %}
                                <input type="submit" value="Add Favorite" />
                                {% endif %}
                            </form>
                        </p>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <p>No authored recipes yet!</p>
            {% endif %}
        </ul>
        <h3>Favorited Recipes:</h3>
        <ul>
            {% if favorites %}
            {% for item in favorites %}
            <div class="col-md-4">
                <div class="card">
                    <a href="{% url 'recipes:recipe' item.pk %}">
                        {% if item.img %}
                        <img src="{% static ''%}{{ item.img }}" class="card-img-top" alt="...">
                        {% endif %}
                    </a>
                    <div class="card-body">
                        <h5 class="card-title">{{ item.recipe_title }}</h5>
                        <p class="card-text">
                            <a href="{% url 'recipes:recipe' item.pk %}">View this Recipe</a> 
                            <form action="{% url 'recipes:favorite' item.id user.id %}" method='POST'>
                                {% csrf_token %}
                                <input type="hidden" name="next" value="{{ request.path }}">
                                <input type="submit" value="Remove Favorite">
                            </form>
                        </p>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <p>No favorited recipes yet!</p>
            {% endif %}
        </ul>   
    </div>

    

    <form action="{% url 'recipes:editprofile' profile.id %}">
        <input type="submit" value="Edit Profile" />
    </form>
</div>

    {% endblock %}

recipes/templates/recipes/recipe.html
{% extends "recipes/base.html" %}

{% load static %}
{% load custom_tags %}

{% block description %}Recipe information for {{ recipe.recipe_title }}{% endblock %}
{% block title %}{{ recipe.recipe_title }}{% endblock %}


{% block content %}

<div class="container main bg-light">
    <div class="row banner">
        <div class="col-8 col-md-9">
            <h1>{{ recipe.recipe_title }}</h1>
            {% if recipe.parent %}
            <h5>Forked from <a href="{% url 'recipes:recipe' recipe.parent.id %}">{{ recipe.parent.recipe_title }}</a></h5>
            {% endif %}
        </div>

        <div class="col-4 col-md-3">
<!--            Favorites Button-->
            <div class="row">
                <div class="favorites-form">
                    {% if user.is_authenticated %}
                    <form action="{% url 'recipes:favorite' recipe.id user.id %}" method='POST' id="favorites-btn">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ request.path }}">

                        {% if user in user_set %}
                        <a href="#" onclick="document.getElementById('favorites-btn').submit();">
                            <i class="fas fa-heart js-heart heart active" id="heart"></i></a>
                        Remove from favorites
                        {% else %}
                        <a href="#" onclick="document.getElementById('favorites-btn').submit();">
                            <i class="far fa-heart js-heart heart inactive" id="heart"></i></a>
                        Add to favorites
                        {% endif %}
                    </form>
                    {% endif %}
                </div>
            </div>

<!--            Top Forking Button-->
            <div class="row top-fork-button">
                <span><a href="{% url 'recipes:forkrecipe' recipe.id %}"><button type="button" class="btn btn-primary">
                    <i class="fa fa-utensils"></i></i> Fork Recipe</button></a>
                </span>
            </div>


        </div>

    </div>

    <div class="row">
    <!--        Block with the image-->
        <div class="col-4">
            {% if recipe.img %}
            <img src="{% static ''%}{{ recipe.img }}" class="recipe-img">
            {% endif %}
        </div>

    <!--        Block with the ingredients-->
        <div class="col-8 ingredients">
            <h3>Ingredients</h3>
            <ul>
                {% string_to_list recipe.recipe_ingredients as ingredients %}
                {% for element in ingredients %}

                <li>{{ element }} </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <hr>

    <!--        Ideally block with all the instructions goes here.-->
    <div class="row instructions">
        <h3>Instructions</h3>
         <ol>
            {% string_to_list recipe.recipe_instructions as instructions %}
            {% for element in instructions %}

            <li>{{ element }} </li>
            <br>
            {% endfor %}
        </ol>
    </div>
    <hr>

    <!--        And forks go here. -->
    <div class="row list-of-forks">
        <div class="col-4 col-md-2">
            <h5>Add your own twist:</h5>
            <a href="{% url 'recipes:forkrecipe' recipe.id %}"><button type="button" class="btn btn-primary"><i class="fa fa-utensils"></i></i> Fork Recipe</button></a>
        </div>
        <div class="col-8 col-md-10">
            {% if recipe.recipe_set.all %}
                Forks others have made:<br>
                <ul>
                {% for element in recipe.recipe_set.all %}
                    <li><a href="{% url 'recipes:recipe' element.id %}">{{ element.recipe_title }}</a></li>
                {% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>
</div>

<hr class="comments-hr">

<div class="container bg-light comments">
    <div class="row comments-posted text-center">
        {% load comments %}
        <p>
        {% get_comment_count for object as comment_count %}
            {{ comment_count }} comment{{ comment_count|pluralize }}
            ha{{ comment_count|pluralize:"s,ve" }} been posted.
        </p>
    </div>

    {% if comment_count %}
    <div class="comment-list">
      {% render_comment_list for object %}
    </div>
    {% endif %}
    <div class="card card-block mb-5 comment-submission">
      <div class="card-body">
        <h4 class="card-title text-center pb-3">Post your comment</h4>
          {% render_comment_form for object %}
      </div>
    </div>
</div>


{% endblock %}

recipes/templates/recipes/recipeform.html
{% extends "recipes/base.html" %} {% load socialaccount %}

{% load static %}
{% load custom_tags %}

{% block description %}Add a recipe{% endblock %}
{% block title %}Add a recipe{% endblock %}


{% block content %}

<div class="container main bg-light">
    <div class="row banner">
        {% if form.is_bound %}
            <h1>Fork a Recipe</h1>
        {% else %}
            <h1>Submit a New Recipe</h1>
        {% endif %}
    </div>

    {% if user.is_authenticated %}
    <div class="row">
        <div class="col-8 recipe-submission">
            {% if form.is_bound %}
            <form action="{% url 'recipes:forkrecipe' recipe.id %}" method="post" enctype="multipart/form-data">
                {% else %}
                <form action="{% url 'recipes:recipeform' %}" method="post" enctype="multipart/form-data">
                    {% endif %}
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" value="Submit">
                </form>
            </form>
        </div>
    </div>

    {% else %}
    <div class="row">
        <p>Please login to be able to submit a recipe.</p>
        <a class="nav-link" href="{% provider_login_url 'google' %}?next={{request.path}}"><button type="button" class="btn btn-primary">Login With Google</button></a>
    </div>

    {% endif %}

</div>


{% endblock %}

recipes/templates/recipes/recipelist.html
{% extends "recipes/base.html" %}

{% load static %}
{% load custom_tags %}

{% block description %}List of Recipes{% endblock %}
{% block title %}List of Recipes{% endblock %}

{% block content %}


<div class="container recipe-list">
    {% if recipes_list %}
    {% for recipe in recipes_list %}
    <a href="{% url 'recipes:recipe' recipe.id %}" class="recipe-link">
    <div class="recipe-list-container">
        <div class="row">
            <div class="col-md-4">
                {% if recipe.img %}
                <img src="{% static ''%}{{ recipe.img }}" style="object-fit: contain;" alt="Image of {{ recipe.recipe_title }}">
                {% else %}
                <img src="{% static 'noimage.png'%}" alt="No image">
                {% endif %}
            </div>
            <div class="col-md-8">
                <div class="container__text">
                    <h2>{{ recipe.recipe_title }}</h2>

<!--                    Favorites info div here-->
                    <div class="container__text__heart">
                        {% if recipe.num_favs == 0 %}
                            <i class="far fa-heart heart"></i>
                        {% else %}
                            <i class="fas fa-heart heart"></i>
                        {% endif %}
                        Favorited {{ recipe.num_favs }} time{{ recipe.num_favs | pluralize:",s" }}
                    </div>

                    <p>
<!--                        Description would go here!-->
                    </p>

                    <div class="container__text__timing">
                        <!--             <div class="container__text__timing_time">
                                        <h2>Hands-on Time</h2>
                                        <p>30 min</p>
                                    </div>
                                    <div class="container__text__timing_time">
                                        <h2>Total Time</h2>
                                        <p>40 min</p>
                                    </div>
                                    <div class="container__text__timing_time">
                                        <h2>Yield</h2>
                                        <p>40 min</p>
                                    </div> -->
                    </div>

                        <button class="btn">view recipe <i class="fa fa-arrow-right"></i></button>

                </div>
            </div>
        </div>
    </div>
    </a>
    {% endfor %}

    {% else %}
    <p>Waiting for recipes.</p>
    {% endif %}

</div>

{% endblock %}